name: example-environment
channels:
  - conda-forge
  - Trentonoliphant
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - datetime
  - ipywidgets
  - urllib
  - warnings
