name: cinergi-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - ipywidgets
  - owslib
  - geojson
  - shapely
  - geopandas
  - geojsonio
  - gdal
  - geos
  - lxml
  - requests
  - json
  - pip
  - pip:
